### ISSUE TITLE
benchmark is no fair.

### ISSUE THREAD

**Issue by 2vg** [mattaylor/whip#1]
i read the benchmark code.
it seems that the benchmark is not fair.
the data to be transmitted is different between whip and http beast.

if you look at this you will see the difference in the data being sent.

whip:
```nim
# json
const JSON_DATA = $(%*{"result": "hello world"})

# plain
const TEXT_DATA = "Hello World"
```

httpbeast:
```nim
# json
const data = $(%*{"message": "Hello, World!"})
const headers = "Content-Type: application/json"

# plain
const data = "Hello, World!"
const headers = "Content-Type: text/plain"
```

in whip, `{"result": "hello world"}` and `"Hello World"`
in httpbeast, `{"message": "Hello, World!"} + "Content-Type: application/json"` and `"Hello, World!" + "Content-Type: text/plain"`

in whip, both json and plaintext sent data is different from httpbeast and there are no headers to send.

**Comment by mattaylor** [comment]
Actually whip.send is simply a wrapper around httpbeast.send. The headers are the same. I believe the perf difference is largely due to the routing as Whip uses a hashtable, and the difference is barely significant.

**Comment by mattaylor** [comment]
I have updated the bench code as requested - it of course still makes no difference. (see line 19 from whip.nim)
The latest test I have run show about 8% improvement on beast on simple routes. 
Feel free to run bench.sh and edit as necessary to confirm this. 
Numbers aside the comparison with httpbeast is largely academic as the principle value add that whip brings is routing with query and path parameters, which beast does not support. Jester does all this and more but is 2-3x slower.

**Comment by mattaylor** [comment]
Actually there was a bug in the bench.sh code - procs were not getting killed. This is now fixed. The numbers now look more reasonable - for simple gets, httpbeast is still king.

```bash
Benchmarking Whip

Running 10s test @ http://localhost:8000/text
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   155.32us   43.19us   1.91ms   89.95%
    Req/Sec    31.42k     2.24k   34.00k    91.58%
  631679 requests in 10.10s, 79.52MB read
Requests/sec:  62541.16
Transfer/sec:      7.87MB

------------------------------------------
./bench.sh: line 3: 74705 Killed: 9               ./whipIt > /dev/null 2>&1

Benchmarking Beast

Running 10s test @ http://localhost:8080/text
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   146.29us   59.38us   2.03ms   85.87%
    Req/Sec    32.95k     6.68k   42.13k    69.80%
  661963 requests in 10.10s, 83.33MB read
Requests/sec:  65543.32
Transfer/sec:      8.25MB
```

**Comment by 2vg** [comment]
good

**Comment by mattaylor** [comment]
FYI I added mofuw to the bench tests - results are not good. 
see (https://github.com/mattaylor/whip/blob/master/tests/results1.txt)
You might have some ideas about how to tweak the testcode (https://github.com/mattaylor/whip/blob/master/tests/mofuIt.nim)
