### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by waghanza** [mattaylor/whip#4]
Hi @mattaylor,

Try compilation causes 
```nim
whip.nim(1, 32) Error: cannot open file: packedjson
       Tip: 7 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
```

`packedjson` is required in
https://github.com/mattaylor/whip/blob/b5215cadc284b6e2c010c71c8ade0088c51ddd37/whip.nim#L1 but not defined in `nimble` manifest

Regards,

**Comment by mattaylor** [comment]
I'll fix this tonight.

**Comment by mattaylor** [comment]
done
